sudo: false
language: python

matrix:
  include:
      - python: 3.6
      - python: 3.7

install:
  - travis_retry pip install . pytest isort black mypy readme_renderer
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - ./tests/run_tests.py

  # Check wheather the imports were sorted correctly.
  - isort -c -rc ptpython tests setup.py examples

  - black --check ptpython setup.py examples

  # Type checking
  - mypy ptpython

  # Ensure that the README renders correctly (required for uploading to PyPI).
  - python -m readme_renderer README.rst > /dev/null
